name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: npm install && npm run build
    - name: Firebase Deploy
      run: npm install -g firebase-tools &&
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}